name: Build and Publish

on:
  push:
    branches:
      - master
  release:
    types: [created]

env:
  GIT_USER: 'GitHub Actions'
  GIT_EMAIL: '41898282+github-actions[bot]@users.noreply.github.com'
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install npm dependencies
      #   run: yarn
      # - name: Run linter
        run: yarn lint
      - name: Run unit tests
        run: yarn test
      - name: Report coverage
        run: yarn codecov
      - name: Upload bundle artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Build app
        run: yarn build
      - name: Upload app artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: TriPSs/conventional-changelog-action@v3
  #       with:
  #         github-token: ${{ secrets.GH_TOKEN }}
  #         git-user-name: ${{ env.GIT_USER }}
  #         git-user-email: ${{ env.GIT_EMAIL }}
  #         tag-prefix: 'v'
  #         release-count: '0'
  #         skip-on-empty: false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Pull latest
        run: git pull origin master
      - name: Download bundle artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Create CNAME Record
        run: echo "vuelitaire.com" > dist/CNAME
      - name: Deploy app to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_CONFIG_NAME: ${{ env.GIT_USER }}
          GIT_CONFIG_EMAIL: ${{ env.GIT_EMAIL }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
